name: Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
            ~/.m2
          key: ${{ runner.os }}-cache-${{ hashFiles('**/*.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Trigger Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: auto-build-trigger
